export const START_EXAMINATION = "START_EXAMINATION";
export const SET_USER_ID = "SET_USER_ID";
export const MOVE_NEXT_QUESTION = "MOVE_NEXT_QUESTION";
export const MOVE_PREV_QUESTION = "MOVE_PREV_QUESTION";
export const PUSH_RESULT_ACTION = "PUSH_RESULT_ACTION";
export const RESET_QUESTION_REDUCER = "RESET_QUESTION_REDUCER";
export const RESET_RESULT_REDUCER = "RESET_RESULT_REDUCER";
export const UPDATE_RESULT_ACTION = "UPDATE_RESULT_ACTION";
